import {useState} from 'react';
import {Avatar} from './Avatar';
import {Character,defaultCharacter,hairStyles,hairColors,skinColors,outfits,outfitColors} from './character';
export function Creator({initial,name,onSave,onClose}:{initial?:Character;name:string;onSave:(name:string,c:Character)=>void;onClose?:()=>void}){
 const [c,setC]=useState<Character>(initial??defaultCharacter),[n,setN]=useState(name),[direction,setDirection]=useState(2),[walk,setWalk]=useState(true);
 const update=(patch:Partial<Character>)=>setC(old=>({...old,...patch}));
 function swatches(label:string,values:string[],field:'skin'|'hairColor'|'outfitColor'){return <fieldset><legend>{label}</legend><div className="swatches">{values.map((v,i)=><button type="button" aria-label={`${label} ${i+1}`} aria-pressed={c[field]===v} style={{background:v}} key={v} onClick={()=>update({[field]:v})}>{c[field]===v?'✓':''}</button>)}</div></fieldset>;}
 return <form className="creator" onSubmit={e=>{e.preventDefault();if(n.trim())onSave(n.trim(),c);}}><div className="dialog-heading"><div><small>YOUR JOURNEY STARTS HERE</small><h1>{initial?'나의 캐릭터 꾸미기':'나만의 연구원 만들기'}</h1></div>{onClose&&<button type="button" onClick={onClose}>닫기 ×</button>}</div><div className="creator-grid"><div className="character-stage"><span className="stage-label">LIVE PREVIEW</span><Avatar character={c} size={256} walking={walk} direction={direction}/><strong>{n||'새로운 연구원'}</strong><span>반도체 아카데미 · 신입 연구원</span><div className="rotation">{['뒤','왼쪽','앞','오른쪽'].map((v,i)=><button type="button" aria-pressed={direction===i} onClick={()=>setDirection(i)} key={v}>{v}</button>)}</div><button type="button" onClick={()=>setWalk(!walk)}>{walk?'걷기 미리보기 일시정지':'걷기 미리보기'}</button><p>모든 헤어와 복장은 성별에 관계없이<br/>자유롭게 조합할 수 있어요.</p></div><div className="character-options"><label className="name-label">캐릭터 이름<input autoFocus value={n} maxLength={20} required placeholder="이름을 입력하세요" onChange={e=>setN(e.target.value)}/></label><fieldset><legend>성별</legend><div className="choices">{[['male','남성'],['female','여성'],['neutral','선택 안 함']].map(([v,l])=><button type="button" key={v} aria-pressed={c.gender===v} onClick={()=>update({gender:v as Character['gender'],...(v!=='neutral'?{body:v as Character['body']}:{})})}>{l}</button>)}</div></fieldset><fieldset><legend>체형</legend><div className="choices">{[['male','체형 A'],['female','체형 B']].map(([v,l])=><button key={v} type="button" aria-pressed={c.body===v} onClick={()=>update({body:v as Character['body']})}>{l}</button>)}</div></fieldset>{swatches('피부색',skinColors,'skin')}<fieldset><legend>헤어스타일</legend><div className="choices hair-choices">{hairStyles.map(([v,l])=><button type="button" key={v} aria-pressed={c.hair===v} onClick={()=>update({hair:v})}>{l}</button>)}</div></fieldset>{swatches('머리색',hairColors,'hairColor')}<fieldset><legend>복장</legend><div className="choices">{outfits.map(([v,l])=><button type="button" key={v} aria-pressed={c.outfit===v} onClick={()=>update({outfit:v})}>{l}</button>)}</div></fieldset>{swatches('복장 색상',outfitColors,'outfitColor')}<fieldset><legend>액세서리</legend><div className="choices"><button type="button" aria-pressed={c.accessory==='none'} onClick={()=>update({accessory:'none'})}>없음</button><button type="button" aria-pressed={c.accessory==='glasses'} onClick={()=>update({accessory:'glasses'})}>안경</button></div></fieldset></div></div><div className="creator-footer"><p>외형은 나중에도 변경할 수 있어요.<br/><small>이 브라우저에 저장 · 기기 간 동기화는 아직 지원하지 않습니다.</small></p><button className="primary" disabled={!n.trim()}>{initial?'외형 저장':'아카데미로 출발 →'}</button></div></form>;
}
