import {useEffect,useRef,useState} from 'react';
import {MosfetSection,WorkingMosfet} from './FetProcessGame';
import {scientific} from './progression.mjs';
export type ContentData={questions?:ContentData[];questId?:number;questionId?:string;batchId?:string;sessionId?:string;title?:string;question?:string;options?:{id:string;text:string}[];steps?:{id:string;title:string;detail:string}[];correct?:boolean;stageComplete?:boolean;solved?:number;total?:number;explanation?:string;dose?:number;coins?:number;index?:number;message?:string};
export type ContentRequest=(action:'learningStart'|'learningAnswer',args:Record<string,unknown>)=>Promise<ContentData>;
export function LearningQuiz({request,stage,questId,onCorrect,onBusy,practice=false}:{request:ContentRequest;stage:number;questId:number;onCorrect?:(r:ContentData)=>void;onBusy:(busy:boolean)=>void;practice?:boolean}){
 const [data,setData]=useState<ContentData|null>(null),[choice,setChoice]=useState(''),[feedback,setFeedback]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[retry,setRetry]=useState(0);
 const pending=useRef(false),api=useRef(request);api.current=request;
 useEffect(()=>{let alive=true;setBusy(true);onBusy(true);setError('');setData(null);setDone(false);setChoice('');setFeedback('');
 api.current('learningStart',{stage,questId,kind:'quiz'}).then(r=>{if(alive)setData(r);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive){setBusy(false);onBusy(false);}});
 return()=>{alive=false;onBusy(false);};},[stage,questId,retry]);
 const check=async()=>{if(!data||pending.current||done)return;pending.current=true;setBusy(true);onBusy(true);setError('');try{const r=await request('learningAnswer',{sessionId:data.sessionId,optionId:choice});setFeedback(r.explanation||'');if(r.correct){setDone(true);onCorrect?.(r);}}catch(e){setError(e instanceof Error?e.message:'통신 오류');}finally{pending.current=false;setBusy(false);onBusy(false);}};
 return <section>{practice&&<p>복습은 완료 보상을 중복 지급하지 않습니다.</p>}{data&&<><h3>{data.title}</h3><p className="question">{data.question}</p>{!practice&&<p>불순물 +{scientific(data.dose||0)} cm⁻³ · {data.coins} 코인</p>}<div className="answers">{data.options?.map((o,i)=><button key={o.id} disabled={busy||done} aria-pressed={choice===o.id} onClick={()=>setChoice(o.id)}><b>{i+1}</b>{o.text}</button>)}</div><button className="primary" disabled={busy||!choice||done} onClick={()=>void check()}>{busy?'서버 확인 중…':done?'정답입니다':'정답 확인'}</button>{feedback&&<p role="status">{feedback}</p>}{practice&&done&&<button onClick={()=>setRetry(n=>n+1)}>다른 문제 풀기</button>}</>}{busy&&!data&&<p role="status">문제를 불러오고 있습니다…</p>}{error&&<><p role="alert">{error}</p><button disabled={busy} onClick={()=>setRetry(n=>n+1)}>문제 다시 불러오기</button></>}</section>;
}
const diagramIds=['substrate','oxide','gate','implant','anneal','contacts'];
export function LearningExperiment({request,onComplete,onBusy,completed}:{request:ContentRequest;onComplete:()=>void;onBusy:(v:boolean)=>void;completed:boolean}){
 const [data,setData]=useState<ContentData|null>(null),[order,setOrder]=useState<string[]>([]),[result,setResult]=useState<ContentData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);const pending=useRef(false),api=useRef(request);api.current=request;
 useEffect(()=>{let alive=true;setBusy(true);onBusy(true);setError('');setData(null);setOrder([]);setResult(null);api.current('learningStart',{stage:7,kind:'experiment'}).then(r=>{if(alive)setData(r);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive){setBusy(false);onBusy(false);}});return()=>{alive=false;onBusy(false);};},[retry]);
 const check=async()=>{if(!data||pending.current)return;pending.current=true;setBusy(true);onBusy(true);try{const r=await request('learningAnswer',{sessionId:data.sessionId,order});setResult(r);if(r.correct)onComplete();}catch(e){setError(e instanceof Error?e.message:'서버 연결 오류');}finally{pending.current=false;setBusy(false);onBusy(false);}};
 return <section className="fet-game"><h3>{data?.title||'실험 과제'}</h3>{completed&&<p>✓ 이전 완료 기록이 있습니다.</p>}{result?.correct?<><p>{result.message}</p><WorkingMosfet/><button onClick={()=>setRetry(n=>n+1)}>다시 도전</button></>:<><ol className="fet-order">{order.map((id,i)=>{const s=data?.steps?.find(s=>s.id===id);return <li key={id}><MosfetSection step={diagramIds.indexOf(id)}/><strong>{i+1}. {s?.title}</strong><button disabled={busy||i===0} onClick={()=>{const next=[...order];[next[i-1],next[i]]=[next[i],next[i-1]];setOrder(next);setResult(null);}}>←</button><button disabled={busy||i===order.length-1} onClick={()=>{const next=[...order];[next[i+1],next[i]]=[next[i],next[i+1]];setOrder(next);setResult(null);}}>→</button><button disabled={busy} onClick={()=>{setOrder(order.filter(x=>x!==id));setResult(null);}}>빼기</button></li>;})}</ol><div className="fet-bank">{data?.steps?.filter(s=>!order.includes(s.id)).map(s=><button className="fet-card" key={s.id} disabled={busy} onClick={()=>{setOrder([...order,s.id]);setResult(null);}}><MosfetSection step={diagramIds.indexOf(s.id)}/><strong>{s.title}</strong><span>{s.detail}</span></button>)}</div>{data&&<button className="primary" disabled={busy||order.length!==data.steps?.length} onClick={()=>void check()}>공정 순서 확인</button>}{result&&<p role="status">{result.message}</p>}</>}{busy&&<p role="status">서버 확인 중…</p>}{error&&<><p role="alert">{error}</p><button disabled={busy} onClick={()=>setRetry(n=>n+1)}>다시 불러오기</button></>}</section>;
}
