import {useEffect,useRef,useState,ReactNode} from 'react';
import {createRoot} from 'react-dom/client';
import {World} from './World';
import {Avatar} from './Avatar';
import {Creator} from './Creator';
import {Character,defaultCharacter,validCharacter} from './character';
import {quests} from './quests';
import {stages,level} from './physics.mjs';
import './style.css';
import './touch.css';
type Save={version:2;name:string;character:Character;completed:number[]};
function restore():Save|null{try{const s=JSON.parse(localStorage.getItem('doping-heroes:v2')||localStorage.getItem('doping-heroes:v1')||'null');if(!s||typeof s.name!=='string'||!s.name.trim()||s.name.length>20||!Array.isArray(s.completed)||s.completed.length>3||!s.completed.every((n:unknown,i:number)=>n===i))return null;return {version:2,name:s.name,character:validCharacter(s.character),completed:s.completed};}catch{return null;}}
const emit=(name:string,detail?:unknown)=>window.dispatchEvent(new CustomEvent(name,{detail}));
function Modal({children,onClose,wide=false,label}:{children:ReactNode;onClose?:()=>void;wide?:boolean;label:string}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className={wide?'modal wide':'modal'} aria-label={label} onCancel={e=>{e.preventDefault();onClose?.();}}>{children}</dialog>;}
function App(){
 const [save,setSave]=useState<Save|null>(restore),[panel,setPanel]=useState<string|null>(null),[editing,setEditing]=useState(false),[pos,setPos]=useState({x:768,y:590}),[toast,setToast]=useState(''),[storageError,setStorageError]=useState(false);
 const [dialog,setDialog]=useState<number|null>(null),[started,setStarted]=useState(false),[choice,setChoice]=useState<number|null>(null),[feedback,setFeedback]=useState(''),[reward,setReward]=useState(false),[selected,setSelected]=useState(0);
 const completed=save?.completed??[],character=save?.character??defaultCharacter,current=stages[selected],q=dialog===null?null:quests[dialog];
 const blocked=!save||editing||!!panel||dialog!==null;
 useEffect(()=>{if(save)try{localStorage.setItem('doping-heroes:v2',JSON.stringify(save));setStorageError(false);}catch{setStorageError(true);}},[save]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'read_learning_progress',description:'Read locally saved character customization and learning progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({character:save?.name??null,appearance:save?.character??null,completed:completed.map(i=>quests[i].title),level:level(completed)})},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[save]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{const reset=()=>emit('lab-direction',{x:0,y:0});window.addEventListener('blur',reset);document.addEventListener('visibilitychange',reset);return()=>{window.removeEventListener('blur',reset);document.removeEventListener('visibilitychange',reset);};},[]);
 const open=(i:number)=>{setPanel(null);setDialog(i);setStarted(false);setChoice(null);setFeedback('');setReward(false);};
 const answer=()=>{if(!q||dialog===null||choice===null||!save)return;if(choice!==q.answer){setFeedback('다시 생각해 보세요. '+(dialog===0?'P의 원자가전자는 5개입니다.':dialog===1?'σ = q(nμₙ + pμₚ)를 떠올려 보세요.':'B는 억셉터로 작용합니다.'));return;}setFeedback(q.explanation);setReward(true);setSelected(dialog+1);if(!completed.includes(dialog))setSave({...save,completed:[...completed,dialog]});};
 const go=(i:number)=>{setPanel(null);requestAnimationFrame(()=>emit('lab-navigate',i));};
 function map(large=false){return <div className={large?'map-image large-map':'map-image'}><img src="./campus.webp" alt="모험가 길드, 상점, 동굴과 다리가 있는 세미 마을 지도"/><span className="you-marker" style={{left:pos.x/1536*100+'%',top:pos.y/1024*100+'%'}} aria-label="내 위치"/>{large&&<div className="map-destinations">{quests.map((quest,i)=><button key={i} onClick={()=>go(i)}>{quest.name}에게 이동</button>)}</div>}</div>;}
 return <main className="rpg">
  <World character={character} name={save?.name??'새로운 모험가'} completed={completed} active={!blocked} onTalk={open} onPosition={(x,y)=>setPos({x,y})} onError={setToast}/>
  <div className="top-left hud"><button className="portrait" onClick={()=>setEditing(true)} aria-label="캐릭터 꾸미기"><Avatar character={character} size={82}/></button><div className="player-status"><div><strong>{save?.name??'새로운 모험가'}</strong><b>Lv. {level(completed)}</b></div><label>모험 <progress value={completed.length} max={3}/><span>{completed.length}/3</span></label><small>세미 월드 · {completed.length===3?'도핑 탐험가':'초보 모험가'}</small></div></div>
  <div className="world-title"><small>SEMI ADVENTURE</small><h1>세미 어드벤처</h1><span>CHAPTER 01 · 세미 마을</span></div>
  <aside className="top-right"><button className="minimap hud" onClick={()=>setPanel('map')} aria-label="세미 마을 지도 열기">{map()}<span>☀ 세미 마을 <small>지도 보기</small></span></button><section className="quest-tracker hud"><button className="tracker-heading" onClick={()=>setPanel('quests')}>오늘의 퀘스트 <span>{completed.length}/3</span></button>{quests.map((quest,i)=><button key={i} className={completed.includes(i)?'finished':''} onClick={()=>i<=completed.length?go(i):setToast('이전 퀘스트를 먼저 완료해 주세요.')}><span>{completed.includes(i)?'✓':'◇'}</span><span>{quest.title.slice(5)}</span><small>{completed.includes(i)?'완료':i===completed.length?'이동':'잠김'}</small></button>)}</section></aside>
  <div className="welcome-ribbon">{completed.length===3?'첫 모험 완료! 도감에서 시료를 비교해 보세요.':'NPC의 ! 표시를 터치하고 첫 모험을 시작하세요.'}</div>
  <div className="bottom-left"><div className="dpad" aria-label="터치 방향키">{[{l:'↑',x:0,y:-1,k:'up'},{l:'←',x:-1,y:0,k:'left'},{l:'↓',x:0,y:1,k:'down'},{l:'→',x:1,y:0,k:'right'}].map(v=><button key={v.k} className={v.k} aria-label={{up:'위로 이동',left:'왼쪽 이동',down:'아래로 이동',right:'오른쪽 이동'}[v.k]} disabled={blocked} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);emit('lab-direction',{x:v.x,y:v.y});}} onPointerUp={()=>emit('lab-direction',{x:0,y:0})} onPointerCancel={()=>emit('lab-direction',{x:0,y:0})} onLostPointerCapture={()=>emit('lab-direction',{x:0,y:0})}>{v.l}</button>)}</div><small>터치 이동 · WASD / 방향키</small></div>
  <nav className="bottom-menu hud" aria-label="게임 메뉴">{[{id:'character',icon:'♙',label:'캐릭터'},{id:'samples',icon:'◈',label:'시료 가방'},{id:'quests',icon:'☷',label:'퀘스트'},{id:'map',icon:'⌘',label:'지도'},{id:'guide',icon:'?',label:'도움말'}].map(item=><button key={item.id} onClick={()=>item.id==='character'?setEditing(true):setPanel(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav>
  <button className="talk-button" disabled={blocked} onClick={()=>emit('lab-talk')}><span>···</span>대화</button>
  {(toast||storageError)&&<div className="toast" role="status">{storageError?'자동 저장을 사용할 수 없습니다. 브라우저 저장 공간을 확인해 주세요.':toast}</div>}
  {(!save||editing)&&<Modal wide label="캐릭터 제작" onClose={save?()=>setEditing(false):undefined}><Creator initial={save?.character} name={save?.name??''} onClose={save?()=>setEditing(false):undefined} onSave={(name,c)=>{setSave({version:2,name,character:c,completed});setEditing(false);setToast('나만의 모험가으로 세미 마을에 입장했습니다.');}}/></Modal>}
  {panel&&<Modal wide={panel==='map'} label={panel} onClose={()=>setPanel(null)}><div className="dialog-heading"><div><small>ADVENTURE LOG</small><h2>{{map:'세미 마을 지도',quests:'오늘의 퀘스트',samples:'나의 반도체 시료',guide:'탐험 안내'}[panel]}</h2></div><button onClick={()=>setPanel(null)}>닫기 ×</button></div>
   {panel==='map'&&<>{map(true)}<p>목적지를 선택하면 길을 따라 이동합니다. 물과 건물은 통과할 수 없습니다.</p></>}
   {panel==='quests'&&<div className="quest-journal">{quests.map((quest,i)=><article key={i}><h3>{quest.title}</h3><p>{quest.reward}</p><button disabled={i>completed.length} onClick={()=>go(i)}>{completed.includes(i)?'NPC 다시 만나기':i===completed.length?'NPC에게 이동':'이전 퀘스트 완료 필요'}</button><button className="quiet" disabled={i>completed.length} onClick={()=>open(i)}>대화 바로 열기</button></article>)}</div>}
   {panel==='samples'&&<><label>시료 선택<select value={selected} onChange={e=>setSelected(Number(e.target.value))}><option value={0}>순수 Si · 도핑 전</option>{completed.map(i=><option key={i} value={i+1}>{quests[i].reward}</option>)}</select></label><div className="sigma"><small>전도도 σ</small><strong>{current.sigma.toExponential(2)} <span>S/cm</span></strong></div><dl><div><dt>전자 농도</dt><dd>{current.n.toExponential(2)} cm⁻³</dd></div><div><dt>정공 농도</dt><dd>{current.p.toExponential(2)} cm⁻³</dd></div></dl><div className="equation">σ = q(nμₙ + pμₚ)</div><p>300 K · 완전 이온화 · 고정 이동도 근사<br/>μₙ = 1350, μₚ = 480 cm²/(V·s), nᵢ = 10¹⁰ cm⁻³.</p><p>보유 시료의 최고 전도도가 순수 Si 대비 10배 증가할 때마다 레벨이 1 증가합니다. n형과 p형은 독립 시료이며, 같은 시료의 보상 도핑과는 다릅니다.</p></>}
   {panel==='guide'&&<><h3>길을 따라, 나만의 속도로</h3><p>맵 터치: 선택한 곳의 가까운 길로 이동<br/>NPC 터치: 자동 접근 후 대화<br/>방향 패드 / WASD: 직접 이동<br/>대화 버튼 / E: 가까운 NPC와 대화</p><p>캐릭터 메뉴에서 성별, 체형, 피부색, 헤어스타일, 머리색, 복장과 색상을 언제든 변경할 수 있습니다. 외형은 학습 결과에 영향을 주지 않습니다.</p><h3>저장과 학습 모델</h3><p>진행 기록과 외형은 이 브라우저에만 저장됩니다. 공용 기기에서는 이전 사용자의 기록이 보일 수 있습니다. 학생 계정 로그인·Google Sheets·멀티플레이는 아직 연결하지 않았습니다.</p><p>전도도는 학습용 근사 모델입니다. 현재는 세미 마을 외부 탐색과 퀘스트 3개를 플레이할 수 있으며 건물 내부는 아직 없습니다.</p><a href="./ART-CREDITS.txt" target="_blank" rel="noreferrer">캐릭터 아트 출처 및 라이선스 ↗</a><small className="version">세미 어드벤처 v0.2.1</small></>}
  </Modal>}
  {q&&dialog!==null&&<Modal label={q.title} onClose={()=>setDialog(null)}><div className="dialog-heading"><div><small>{q.name} / QUEST {dialog+1}</small><h2>{q.title}</h2></div><button onClick={()=>setDialog(null)}>닫기 ×</button></div>{dialog>completed.length?<p>이전 퀘스트를 먼저 완료해 주세요.</p>:completed.includes(dialog)&&!reward?<><p>퀘스트를 완료했습니다.</p><p>{q.explanation}</p><button className="primary" onClick={()=>{setSelected(dialog+1);setDialog(null);setPanel('samples');}}>시료 관찰하기</button></>:!started?<><p className="npc-line">“{q.question} 함께 수수께끼를 풀어 봅시다.”</p><p className="reward-tag">퀘스트 보상 · {q.reward}</p><button className="primary" onClick={()=>setStarted(true)}>퀘스트 수락</button></>:<><p className="question">{q.question}</p><div className="answers">{q.options.map((o,i)=><button key={o} disabled={reward} aria-pressed={choice===i} onClick={()=>{setChoice(i);setFeedback('');}}><b>{i+1}</b>{o}</button>)}</div>{feedback&&<p className={reward?'feedback success':'feedback'} role="status">{reward?'정답! ':''}{feedback}</p>}{reward?<><div className="doping"><div className="lattice" aria-label="도펀트 치환 개념 애니메이션">{Array.from({length:12},(_,i)=><span key={i} className={i===5?'dopant':''}>{i===5?q.dopant:'Si'}</span>)}</div><p>{q.reward}<br/><strong>시료 획득 · Lv. {level(completed)}</strong></p></div><small>축척과 원자 비율을 단순화한 개념도</small><button className="primary" onClick={()=>setDialog(null)}>탐험 계속하기</button></>:<button className="primary" disabled={choice===null} onClick={answer}>정답 확인</button>}</>}</Modal>}
 </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
