import {catalog,inventoryIds,isConsumable,slotNames} from './catalog.mjs';
import {ItemIcon} from './ItemIcon';
import './catalog.css';
import {isRootAccount} from './access.mjs';
import {canEnterStage,readStageReleases,releaseStage,stageAccessBlock,subscribeStageReleases} from './stage-release.mjs';
import {FetProcessGame} from './FetProcessGame';
import {StageBook} from './StageBook';
import {ItemReveal} from './ItemReveal';
import {SiliconLibrary,PracticeBoard} from './learning';
import {useEffect,useRef,useState,ReactNode} from 'react';
import {createRoot} from 'react-dom/client';
import {World} from './World';
import {Avatar} from './Avatar';
import {ImplantAnimation} from './ImplantAnimation';
import {Creator} from './Creator';
import {mapInfo,stageIndex,stageDefinitions,stageForQuest,gatewayLocations,arrivalPoint,stageUnlocked} from './maps.mjs';
import {Inventory} from './Inventory';
import {defaultCharacter} from './character';
import {availableCharacter,rewardNames,equipment} from './equipment';
import {quests} from './quests';
import {weeklyQuests,shopItems} from './adventure';
import {restore,hasKey,type Save} from './save';
import {grantReward,purchase,grantBookReward,bookDose,useConsumable} from './economy.mjs';
import {progress,conductivity,resistivity,levelLabel,scientific,sigmaLabel,MIN_DOPING,MAX_DOPING} from './progression.mjs';
import './style.css';import './touch.css';import './adventure.css';
const allQuests=[...quests.map((q,i)=>({...q,id:i,week:0,dose:[2e13,3e13,4e13][i],coins:20,name:'길잡이 Dr. 실리콘'})),...weeklyQuests];
const emit=(name:string,detail?:unknown)=>window.dispatchEvent(new CustomEvent(name,{detail}));
function Modal({children,onClose,wide=false,label}:{children:ReactNode;onClose?:()=>void;wide?:boolean;label:string}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className={wide?'modal wide':'modal'} aria-label={label} onCancel={e=>{e.preventDefault();onClose?.();}}>{children}</dialog>;}
function App(){
 const [save,setSave]=useState<Save|null>(restore),[panel,setPanel]=useState<string|null>(null),[editing,setEditing]=useState(false),[arrival,setArrival]=useState<number|null>(null),[destination,setDestination]=useState<number|null>(null),[pos,setPos]=useState({x:768,y:590}),[toast,setToast]=useState(''),[storageError,setStorageError]=useState(false);
 const [dialog,setDialog]=useState<number|null>(null),[choice,setChoice]=useState<number|null>(null),[feedback,setFeedback]=useState(''),[reward,setReward]=useState(false),[implantFrom,setImplantFrom]=useState(MIN_DOPING),[caveExponent,setCaveExponent]=useState(16),[mapArea,setMapArea]=useState<Save['area']>('village');
 const [cinematic,setCinematic]=useState(false);
 const [releasedStages,setReleasedStages]=useState<boolean[]>(readStageReleases);
 const [rewardItems,setRewardItems]=useState<string[]>([]),[implantDone,setImplantDone]=useState(false),[practiceId,setPracticeId]=useState(3);
 const completed=save?.completed??[],character=save?.character??defaultCharacter,area=save?.area??'village',doping=save?.doping??MIN_DOPING,type=save?.type??'n',xp=progress(doping,type),key=hasKey(save),q=dialog===null?null:allQuests[dialog];
 const rootAccount=isRootAccount(save),unlocked=(index:number|undefined)=>canEnterStage(completed,index,rootAccount,releasedStages[index??-1]);
 const stageBlocked=(index:number|undefined)=>stageAccessBlock(completed,index,rootAccount,releasedStages[index??-1])==='admin'?'아직 접근 불가한 Stage입니다.':'이전 Stage 퀘스트를 모두 완료해 주세요.';
 const ownedIds=save?inventoryIds(save):[],counts=Object.fromEntries(['dopant','donor-ampoule','acceptor-ampoule'].map(id=>[id,rootAccount?Math.max(1,save?.quantities?.[id]??0):save?.quantities?.[id]??0]));
 const blocked=cinematic||!save||!save.studentId||editing||!!panel||dialog!==null;
 useEffect(()=>{if(save)try{localStorage.setItem('doping-heroes:v3',JSON.stringify(save));setStorageError(false);}catch{setStorageError(true);}},[save]);
 useEffect(()=>subscribeStageReleases(setReleasedStages),[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{const reset=()=>emit('lab-direction',{x:0,y:0});window.addEventListener('blur',reset);document.addEventListener('visibilitychange',reset);return()=>{window.removeEventListener('blur',reset);document.removeEventListener('visibilitychange',reset);};},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'read_learning_progress',description:'Read local adventure progress without student identifiers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({character:save?.name??null,completed:completed.map(i=>allQuests[i].title),dopantDensityCm3:doping,conductivityScm:xp.sigma,stage:xp.stage,area,bridgeKey:key})},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[save]);
 const openQuest=(i:number)=>{if(i>=3&&!unlocked(stageForQuest(i)?.index)){setToast(stageBlocked(stageForQuest(i)?.index));return;}setPanel(null);setDialog(i);setChoice(null);setFeedback('');setReward(false);};
 const talk=(i:number)=>{if(area==='village'){if(i===1){setPanel('shop');return;}if(i===2){setPanel('cave');return;}const next=[0,1,2].find(n=>!completed.includes(n));if(next!==undefined)openQuest(next);else setPanel('silicon');}else openQuest(i);};
 const enterStage=(index:number)=>{if(!unlocked(index)){setToast(stageBlocked(index));return;}const target=stageDefinitions[index].area as Save['area'];setDestination(null);setArrival(null);setSave(s=>s?{...s,area:target}:s);setPos(mapInfo(target).spawn);setToast(stageDefinitions[index].title+'에 입장했습니다.');};
 const travel=()=>{if(!save)return;if(!key){setToast('앞선 Stage 퀘스트를 먼저 완료해 주세요. 마을에서는 Dr. 실리콘의 첫걸음을 완료하세요.');return;}const index=stageIndex(area),next:Save['area']=index>=0?'adventure':area==='village'?'adventure':'village';if(area==='adventure')setDestination(null);setArrival(index>=0?index:null);setSave(s=>s?{...s,area:next}:s);setPos(arrivalPoint(next,index>=0?index:null));setToast(index>=0?'관문 앞으로 돌아왔습니다.':next==='adventure'?'북쪽 입구에 도착했어요. 아래로 내려가 Stage 관문을 선택하세요.':'세미 마을에 돌아왔습니다.');};
 const answer=()=>{if(!q||dialog===null||choice===null||!save)return;if(choice!==q.answer){setFeedback('다시 생각해 보세요. '+(q.id===0?'P는 원자가전자가 5개입니다.':q.id===1?'이동도가 일정할 때 σ는 전자 농도에 비례합니다.':q.id===2?'B는 억셉터입니다.':'선택지를 다시 비교해 보세요.'));return;}const next=grantReward(save,q);if(next===save)return;setFeedback(q.explanation);setImplantFrom(doping);setImplantDone(false);setRewardItems([...equipment.filter(i=>i.quest===q.id).map(i=>i.id),...next.purchased.filter((id:string)=>!save.purchased.includes(id))]);setReward(true);setSave(next);};
 const buy=(id:string)=>{const item=shopItems.find(i=>i.id===id);if(!item||!save)return;if(save.coins<item.price){setToast('코인이 부족해요. 퀘스트를 완료해 코인을 모으세요.');return;}if(!isConsumable(id)&&(ownedIds.includes(id)||({cap:completed.includes(1),boots:completed.includes(0),sword:completed.includes(2),cardigan:completed.includes(2)} as Record<string,boolean>)[id]))return;if(isConsumable(id)&&doping>=MAX_DOPING){setToast('최대 도핑 농도에 도달했습니다.');return;}const next=purchase(save,item);const gained=next.purchased.filter((id:string)=>!save.purchased.includes(id));setSave(next);if(gained.length){setRewardItems(gained);setPanel('loot');}setToast(item.name+' 구매 완료!');};
 const go=(id:number)=>{setPanel(null);const target=stageForQuest(id);if(target&&!unlocked(target.index)){setToast(stageBlocked(target.index));return;}if(area==='village'&&id<3)requestAnimationFrame(()=>emit('lab-navigate',0));else if(area==='adventure'&&target)requestAnimationFrame(()=>emit('lab-navigate',id));else if(target?.area===area)requestAnimationFrame(()=>emit('lab-navigate',id));else if(area==='village'&&target&&key){setDestination(target.index);setToast('남쪽 나무 관문을 열고 배에 타면 목적지로 안내합니다.');requestAnimationFrame(()=>emit('lab-map-target',{x:768,y:800}));}else{if(target){setDestination(target.index);}setToast('위쪽 출구로 나와 다음 목적지를 선택하세요.');requestAnimationFrame(()=>emit('lab-map-target',mapInfo(area).exit));}};
 function map(which=area,large=false){const info=mapInfo(which);return <div className={large?'map-image large-map':'map-image'} style={{aspectRatio:`${info.width}/${info.height}`}}><img src={info.image} alt={info.title}/>{which===area&&<span className="you-marker" style={{left:pos.x/info.width*100+'%',top:pos.y/info.height*100+'%'}} aria-label="내 위치"/>}{which==='adventure'&&gatewayLocations.map((p,i)=><button className={large?"region-marker stage-number":"mini-stage-number"} key={i} style={{left:p.x/1536*100+'%',top:p.y/1024*100+'%'}} tabIndex={large?0:-1} aria-hidden={!large} title={stageDefinitions[i].title} onClick={e=>{e.stopPropagation();go(stageDefinitions[i].questId);}} disabled={!unlocked(i)}>{!releasedStages[i]?'🔐':!rootAccount&&!stageUnlocked(completed,i)?'🔒':i+1}</button>)}</div>;}
 return <main className="rpg">
 <World rootAccount={rootAccount} releasedStages={releasedStages} character={character} name={save?.name??'새로운 모험가'} completed={completed} area={area} arrival={arrival} destination={destination} active={!blocked} onTalk={talk} onBook={()=>setPanel('book')} onMiniGame={()=>{if(area==='stage-11')setPanel('fet-game');}} onBusy={setCinematic} onTravel={travel} onReleaseStage={index=>{setReleasedStages(releaseStage(index));setToast(stageDefinitions[index].title+' 관문이 모든 학생에게 공개되었습니다.');}} onEnterStage={enterStage} onPosition={(x,y)=>setPos({x,y})} onError={setToast}/>
 {cinematic&&<div className="cinematic-shield" aria-label="이동 연출 중"/>}
 <div className="top-left hud"><button className="portrait" onClick={()=>setEditing(true)} aria-label="캐릭터 꾸미기"><Avatar character={character} size={82}/></button><div className="player-status"><div><strong>{save?.name??'새로운 모험가'}</strong><b>{levelLabel(doping,type)}</b></div><small>도핑 경험치 · {type==='n'?'n형 P':'p형 B'} · {xp.stage}/9단계</small><div className="doping-range"><span>{scientific(xp.low)}</span><progress aria-label="다음 농도 구간까지 도핑 경험치" value={xp.fraction} max={1}/><span>{scientific(xp.high)}</span></div><small>{scientific(doping)} cm⁻³ {xp.max?'· MAX':''} · ◉ {save?.coins??0} · {key?'🗝 열쇠 보유':'열쇠 없음'}</small></div></div>
 <div className="world-title"><small>SEMI ADVENTURE</small><h1>세미 어드벤처</h1><span>{mapInfo(area).title}</span></div>
 <aside className="top-right"><div role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'){setMapArea(area);setPanel('map');}}} className="minimap hud" onClick={()=>{setMapArea(area);setPanel('map');}} aria-label="전체 지도 열기">{map()}<span>{mapInfo(area).title} <small>전체 지도</small></span></div><section className="quest-tracker hud"><button className="tracker-heading" onClick={()=>setPanel('quests')}>{area==='village'?'Dr. 실리콘의 첫걸음':'Stage 모험'} <span>{area==='village'?completed.filter(i=>i<3).length+'/3':completed.filter(i=>i>=3).length+'/12'}</span></button>{(area==='village'?allQuests.slice(0,3):(stageIndex(area)>=0?allQuests.filter(q=>q.id===stageDefinitions[stageIndex(area)].questId):stageDefinitions.map(s=>allQuests[s.questId]).filter(q=>!completed.includes(q.id)).slice(0,3))).map(quest=><button key={quest.id} className={completed.includes(quest.id)?'finished':''} onClick={()=>go(quest.id)}><span>{completed.includes(quest.id)?'✓':'◇'}</span><span>{quest.week?(stageForQuest(quest.id)?.title+' · '):''}{quest.title.replace(/^0\d · /,'')}</span><small>이동</small></button>)}<button onClick={()=>setPanel('quests')}>전체 퀘스트 {completed.length}/15</button></section></aside>
 <div className="welcome-ribbon">{area==='village'?(key?'열쇠 획득! 남쪽 나무 관문을 터치해 열고 배에 타세요.':'길잡이 Dr. 실리콘을 만나 문제 3개를 풀어 보세요.'):(stageIndex(area)>=0?mapInfo(area).title+' · ← 책 읽기 · 가운데 퀴즈'+(area==='stage-11'?' · ↓ MOSFET 미니게임':''):rootAccount?'관리자 · 잠긴 관문 앞에서 7번 연속 두드려 공개하세요.':'12개 Stage 관문 · 공개된 관문을 직접 터치하세요.')}</div>
 <div className="bottom-left"><div className="dpad" aria-label="터치 방향키">{[{l:'↑',x:0,y:-1,k:'up'},{l:'←',x:-1,y:0,k:'left'},{l:'↓',x:0,y:1,k:'down'},{l:'→',x:1,y:0,k:'right'}].map(v=><button key={v.k} className={v.k} aria-label={v.k+' 이동'} disabled={blocked} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);emit('lab-direction',{x:v.x,y:v.y});}} onPointerUp={()=>emit('lab-direction',{x:0,y:0})} onPointerCancel={()=>emit('lab-direction',{x:0,y:0})} onLostPointerCapture={()=>emit('lab-direction',{x:0,y:0})}>{v.l}</button>)}</div><small>터치 이동 · WASD / 방향키</small></div>
 <nav className="bottom-menu hud" aria-label="게임 메뉴">{[{id:'character',icon:'♙',label:'캐릭터'},{id:'inventory',icon:'▣',label:'인벤토리'},{id:'samples',icon:'◈',label:'도핑 가방'},{id:'quests',icon:'☷',label:'퀘스트'},{id:'map',icon:'⌘',label:'전체 지도'},{id:'guide',icon:'?',label:'도움말'}].map(item=><button key={item.id} onClick={()=>{if(item.id==='character')setEditing(true);else{setMapArea(area);setPanel(item.id);}}}><span>{item.icon}</span>{item.label}</button>)}</nav>
 <button className="talk-button" disabled={blocked} onClick={()=>emit('lab-talk')}><span>···</span>대화</button>
 {(toast||storageError)&&<div className="toast" role="status">{storageError?'자동 저장을 사용할 수 없습니다. 브라우저 저장 공간을 확인해 주세요.':toast}</div>}
 {(!save||!save.studentId||editing)&&<Modal wide label="캐릭터 제작" onClose={save?.studentId?()=>setEditing(false):undefined}><Creator initial={save?.character} name={save?.name??''} studentId={save?.studentId??''} completed={completed} purchased={ownedIds} onClose={save?.studentId?()=>setEditing(false):undefined} onSave={(name,c,studentId)=>{setSave(s=>({...s,version:3,name,studentId,character:availableCharacter(c,s?.completed??[],inventoryIds({...s,name,studentId})),completed:s?.completed??[],readBooks:s?.readBooks??[],doping:s?.doping??MIN_DOPING,type:s?.type??'n',coins:s?.coins??0,purchased:s?.purchased??[],area:s?.area??'village'}));setEditing(false);}}/></Modal>}
 {panel&&<Modal wide={['map','quests','cave','fet-game'].includes(panel)} label={panel} onClose={()=>setPanel(null)}><div className="dialog-heading"><div><small>SEMI ADVENTURE</small><h2>{{map:'전체 모험 지도',quests:'모험 기록',samples:'도핑 가방',guide:'탐험 안내',inventory:'인벤토리',shop:'도너 상점',cave:'실리콘 결정 동굴',silicon:'길잡이 Dr. 실리콘',library:'실리콘의 용어 사전',faq:'실리콘의 FAQ',practice:'Stage 복습',loot:'장비 획득',book:'낡은 강의 노트','fet-game':'FET 정글 · MOSFET 공정 퍼즐'}[panel]}</h2></div><button onClick={()=>setPanel(null)}>닫기 ×</button></div>
 {panel==='silicon'&&<><p className="silicon-speech">무엇이 궁금하니?<br/>무엇이든 물어보렴</p><div className="choices"><button onClick={()=>setPanel('library')}>용어 사전</button><button onClick={()=>setPanel('faq')}>FAQ 살펴보기</button></div></>}
 {(panel==='library'||panel==='faq')&&<SiliconLibrary key={panel} initialTab={panel==='faq'?'faq':'terms'}/>}
 {panel==='fet-game'&&area==='stage-11'&&<FetProcessGame completed={save?.fetPuzzleCompleted??false} onComplete={()=>setSave(s=>s?{...s,fetPuzzleCompleted:true}:s)}/>}
 {panel==='book'&&stageIndex(area)>=0&&<StageBook key={area} stage={stageIndex(area)} completed={save?.readBooks?.includes(stageIndex(area))??false} onComplete={()=>{const index=stageIndex(area);setSave(s=>s?grantBookReward(s,index):s);}}/>}
 {panel==='practice'&&<PracticeBoard key={practiceId} quest={allQuests[practiceId]}/>}
 {panel==='loot'&&<ItemReveal ids={rewardItems}/>}
 {panel==='inventory'&&save&&<Inventory character={character} completed={completed} purchased={ownedIds} quantities={counts} onUse={id=>{if(!save)return;const next=useConsumable(save,id);setSave(next);setToast(next===save?'현재는 사용할 수 없습니다.':'소모품을 사용했습니다.');}} onEquip={c=>setSave(s=>s?{...s,character:availableCharacter(c,s.completed,inventoryIds(s))}:s)}/>}
 {panel==='map'&&<><div className="choices"><button aria-pressed={mapArea==='village'} onClick={()=>setMapArea('village')}>세미 마을</button><button aria-pressed={mapArea==='adventure'} onClick={()=>setMapArea('adventure')}>12개 Stage 관문</button>{stageIndex(area)>=0&&<button aria-pressed={mapArea===area} onClick={()=>setMapArea(area)}>현재 Stage</button>}</div>{map(mapArea,true)}<div className="topic-destinations"><h3>Stage 목적지</h3><div className="choices">{stageDefinitions.map(s=><button key={s.index} disabled={!unlocked(s.index)} onClick={()=>go(s.questId)}>{s.title}</button>)}</div></div><p>{key?'마을 남쪽 나무 관문 → 배 탑승 → 대륙 북쪽 입구 → Stage 관문 → 주제별 맵. Stage의 위쪽 출구로 돌아오면 방금 들어간 관문 앞입니다.':'Dr. 실리콘의 문제 3개를 풀면 열쇠를 받고 남쪽 나무 관문을 직접 열 수 있습니다.'}</p></>}
 {panel==='quests'&&<><p>시작 마을의 문제 3개를 완료한 뒤, Stage 1부터 순서대로 퀘스트를 완료하세요. 완료한 Stage는 언제든 복습할 수 있습니다.</p><div className="quest-journal weekly-journal">{[...allQuests.slice(0,3),...stageDefinitions.map(s=>allQuests[s.questId])].map(quest=><article key={quest.id}><small>{quest.week?stageForQuest(quest.id)?.title:'튜토리얼 · Dr. 실리콘'}</small><h3>{completed.includes(quest.id)?'✓ ':''}{quest.title}</h3><p>불순물 +{scientific(quest.dose)} cm⁻³ · {quest.coins} 코인</p>{quest.id<3&&<p>장비 · {rewardNames(quest.id)}</p>}<button disabled={quest.id>=3&&!unlocked(stageForQuest(quest.id)?.index)} onClick={()=>go(quest.id)}>{completed.includes(quest.id)?'다시 만나기':'이동하기'}</button></article>)}</div></>}
 {panel==='samples'&&<><div className="sigma"><small>전도도 레벨 · {xp.stage}/9단계</small><strong>{levelLabel(doping,type)}</strong></div><label>현재 시료 종류<select value={type} onChange={e=>setSave(s=>s?{...s,type:e.target.value==='p'?'p':'n'}:s)}><option value="n">n-Si · 인(P)</option><option value="p">p-Si · 붕소(B)</option></select></label><p>불순물 꾸러미는 인벤토리에서 사용하면 선택한 시료의 도핑 경험치에 반영됩니다. 종류 전환은 같은 농도의 독립 시료 비교이며 보상 도핑을 뜻하지 않습니다.</p><div className="doping-range"><span>{scientific(xp.low)}</span><progress max={1} value={xp.fraction}/><span>{scientific(xp.high)}</span></div><p>현재 농도 {scientific(doping)} cm⁻³ · {xp.max?'최종 구간 완료':'다음 단계까지 '+scientific(xp.high-doping)+' cm⁻³'}</p><p>전도도 표시는 현재 도핑 농도에 따라 갱신됩니다. 현재 농도의 그래프 추정 전도도는 {sigmaLabel(conductivity(doping,type))} S/cm입니다.</p><div className="equation">σ [S/cm] = 1 / ρ [Ω·cm]</div><p>첨부 비저항 그래프를 판독하고 로그 보간한 근삿값입니다. 원자료가 없어 정확한 물성 측정값을 뜻하지 않습니다. 최대 경험치 구간은 1e20 → 1e21 cm⁻³입니다.</p></>}
 {panel==='shop'&&<><p className="shop-balance">보유 코인 ◉ {save?.coins??0}</p><p>소모품은 구입 후 인벤토리에서 사용하세요.</p>{Object.entries(slotNames).map(([slot,label])=><section className="catalog-shop" key={slot}><h3>{label}</h3><div className="shop-grid">{shopItems.filter(item=>item.slot===slot).map(item=>{const owned=!isConsumable(item.id)&&ownedIds.includes(item.id);return <article key={item.id}><ItemIcon id={item.id}/><span className="catalog-code"> {item.code}</span><h3>{item.name}</h3><p>{item.description}</p><button disabled={owned||(save?.coins??0)<item.price} onClick={()=>buy(item.id)}>{owned?'보유 중':item.price+' 코인 · 구매'}</button></article>;})}</div></section>)}</>}
 {panel==='cave'&&<><h3>결정의 메아리 · n형과 p형 비교</h3><p>슬라이더로 도핑 농도를 바꾸고 두 결정의 비저항과 전도도를 비교해 보세요. 이 실험은 경험치와 불순물을 소모하지 않습니다.</p><label>도핑 농도 {scientific(10**caveExponent)} cm⁻³<input className="cave-slider" type="range" min={13} max={21} step={.1} value={caveExponent} onChange={e=>setCaveExponent(Number(e.target.value))}/></label><div className="crystal-results">{(['n','p'] as const).map(kind=><article key={kind}><h3>{kind==='n'?'n-Si · 인(P)':'p-Si · 붕소(B)'}</h3><p>ρ ≈ {sigmaLabel(resistivity(10**caveExponent,kind))} Ω·cm</p><strong>σ ≈ {sigmaLabel(conductivity(10**caveExponent,kind))} S/cm</strong></article>)}</div><p>σ = 1/ρ. 비저항이 낮을수록 전도도가 커집니다. 같은 농도에서도 n형과 p형은 다른 값을 가집니다.</p><small>첨부 그래프 판독·로그 보간에 의한 학습용 근사입니다.</small></>}
 {panel==='guide'&&<><h3>마을에서 대륙으로</h3><p>Dr. 실리콘의 문제 3개 → 열쇠 획득 → 남쪽 나무 관문 터치 → 배 탑승 → 12개 관문과 각각의 별도 Stage 맵. Stage 퀘스트는 순서대로 열리며, 한 번 완료한 보상은 중복 지급되지 않습니다.</p><p>맵/NPC 터치로 이동·대화, 방향 패드 또는 WASD로 직접 이동하세요. 도너 상점에서 물품을 구매하고 결정 동굴에서 n형·p형 전도도를 비교할 수 있습니다.</p><h3>농도가 경험치, 전도도가 레벨</h3><p>불순물을 얻으면 농도가 증가합니다. 1e14, 1e15 … 1e21 cm⁻³ 경계를 넘으면 전도도 레벨이 갱신됩니다. 최대 농도에 도달해도 남은 퀘스트와 코인 보상은 계속 얻을 수 있습니다.</p><p>현재 12개 Stage는 결정·격자·밴드·캐리어·도핑·드리프트·확산·PN 접합·다이오드·BJT·FET·전력 반도체 주제입니다. 실제 강의계획서에 맞춘 내용은 아직 반영되지 않았습니다.</p><h3>저장</h3><p>캐릭터 메뉴에서 이름과 학번을 입력합니다. 학번·진행 기록은 이 브라우저에만 저장되며 학생 인증이나 Google Sheets 동기화는 아직 연결하지 않았습니다. 기존 완료 기록과 외형은 유지됩니다. 접속할 때는 항상 세미 마을에서 시작하며 진행도는 초기화되지 않습니다.</p><a href="./ART-CREDITS.txt" target="_blank" rel="noreferrer">아트 출처 및 라이선스 ↗</a><small className="version">세미 어드벤처 v0.8.0</small></>}
 </Modal>}
 {q&&dialog!==null&&<Modal label={q.title} onClose={()=>setDialog(null)}><div className="dialog-heading"><div><small>{q.name} · {q.week?stageForQuest(q.id)?.title:'첫걸음 '+(q.id+1)+'/3'}</small><h2>{q.title}</h2></div><button onClick={()=>setDialog(null)}>닫기 ×</button></div>{completed.includes(q.id)&&!reward?<><p>{q.explanation}</p><p>퀘스트 달성 ✓ · 보상은 한 번만 지급됩니다.</p>{q.id>=3&&<button onClick={()=>{setPracticeId(q.id);setDialog(null);setPanel('practice');}}>관련 문제 계속 풀기</button>}{q.id===2&&key&&<p className="reward-tag">🗝 모험의 열쇠를 받았습니다. 남쪽 나무 관문을 직접 열어 보세요!</p>}<button className="primary" onClick={()=>setDialog(null)}>모험 계속하기</button></>:<><p className="question">{q.question}</p><p className="reward-tag">불순물 +{scientific(q.dose)} cm⁻³ · {q.coins} 코인{q.id<3&&<> · {rewardNames(q.id)}</>}</p><div className="answers">{q.options.map((o,i)=><button key={o} disabled={reward} aria-pressed={choice===i} onClick={()=>{setChoice(i);setFeedback('');}}><b>{i+1}</b>{o}</button>)}</div>{feedback&&<p className={reward?'feedback success':'feedback'} role="status">{reward?'정답! ':''}{feedback}</p>}{reward?<><ImplantAnimation key={q.id} character={character} before={implantFrom} after={doping} type={type} rewardItems={rewardItems} onComplete={()=>setImplantDone(true)}/>{q.id===2&&key&&<p className="reward-tag">🗝 모험의 열쇠 획득! 남쪽 나무 관문을 터치해 열어 보세요.</p>}<button className="primary" disabled={!implantDone} onClick={()=>{if(q.id<2)openQuest(q.id+1);else setDialog(null);}}>{q.id<2?'Dr. 실리콘의 다음 문제':'모험 계속하기'}</button>{q.id>=3&&<><button onClick={()=>{setPracticeId(q.id);setDialog(null);setPanel('practice');}}>관련 문제 계속 풀기</button>{stageForQuest(q.id)!.index<11&&<button onClick={()=>{setDialog(null);go(stageDefinitions[stageForQuest(q.id)!.index+1].questId);}}>다음 Stage로 이동</button>}</>}</>:<button className="primary" disabled={choice===null} onClick={answer}>정답 확인</button>}</>}</Modal>}
 </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
